#!/bin/bash

if [[ $1 = xinit || $1:$3 = keyboard:connected ]]; then
    setxkbmap -option ctrl:nocaps -option parens:swap_brackets -print | xkbcomp -I"$HOME/.config/xkb" - "$DISPLAY"
fi

if [[ $1 = xinit || $1:$3 = display:connected ]]; then
    if [[ -r $0.displays ]]; then
        connected=$2
        display() {
            [[ -z $connected || $1 = $connected ]] && xrandr --output "$@"
        }
        . "$0.displays"
    else
        xrandr ${2:+--output "$2"} --auto
    fi
elif [[ $1:$3 = display:disconnected ]]; then
    xrandr --output "$2" --off
fi
