#!/bin/bash

if ((!$#)) || [[ $1:$3 = keyboard:connected ]]; then
    setxkbmap -option ctrl:nocaps -option altwin:swap_alt_win
fi

if ((!$#)) || [[ $1:$3 = display:connected ]]; then
    if [[ -f $0.displays ]]; then
        connected=$2
        display() {
            [[ -z $connected ]] && xrandr | grep -q "^$1 connected" || [[ $connected = $1 ]] && xrandr --output "$@"
        }
        source "$0.displays"
        true
    else
        xrandr ${2:+--output "$2"} --auto
    fi
elif [[ $1:$3 = display:disconnected ]]; then
    xrandr --output "$2" --off
fi
