font.size = 9

keyboard.bindings = [
    { action = "CreateNewWindow", key = "Return", mods = "Control" },
    { action = "Paste", key = "P", mode = "Vi|~Search" },
    { action = "ScrollPageUp", key = "PageUp", mode = "Vi" },
    { action = "ScrollPageDown", key = "PageDown", mode = "Vi" },
    { action = "SemanticLeft", key = "Left", mods = "Shift", mode = "Vi|~Search" },
    { action = "SemanticRight", key = "Right", mods = "Shift", mode = "Vi|~Search" },
    { action = "WordLeft", key = "Left", mods = "Control", mode = "Vi|~Search" },
    { action = "WordRight", key = "Right", mods = "Control", mode = "Vi|~Search" },
    { action = "SearchFocusNext", key = "G", mods = "Control", mode = "Search" },
    { action = "SearchFocusPrevious", key = "T", mods = "Control", mode = "Search" },
    { action = "SearchDeleteWord", key = "Back", mods = "Control", mode = "Search" },
    { chars = "\u0017", key = "Back", mods = "Control", mode = "~Vi|~Search" },
]

colors.cursor = { background = "#d8d8d8", text = "#181818" }
colors.vi_mode_cursor = { background = "#d8d8d8", text = "#181818" }
cursor.vi_mode_style.shape = "Block"

hints.alphabet = "ntesiroahdufyw"

[[hints.enabled]]
hyperlinks = true
regex = '(file|https?)://[[:graph:]--"<>\\^`{|}]+|doi:10(\.[0-9]+)+/[^\pZ\pC]+|ar[Xx]iv:([0-9]{4}\.[0-9]{4,5}|[a-z-]+/[0-9]{7})'
post_processing = true
command = "xdg-open"
mouse = { enabled = true, mods = "Control|Shift" }
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex = '(file|https?)://[[:graph:]--"<>\\^`{|}]+|doi:10(\.[0-9]+)+/[^\pZ\pC]+|ar[Xx]iv:([0-9]{4}\.[0-9]{4,5}|[a-z-]+/[0-9]{7})'
post_processing = true
action = "Paste"
binding = { key = "U", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(/?[[:word:].-]+|~[[:word:].-]*)(/[[:word:].-]+)+/?"
post_processing = true
action = "Paste"
binding = { key = "P", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[[:xdigit:]]{6,}"
action = "Paste"
binding = { key = "H", mods = "Control|Shift" }
